review for smart-home-application
CppRemoteLearning/2023 pull request #14
Opened 2023-12-12 00:02 UTC by kyorri

Added the application for review.
I also added a sample file for what the XML file should look like.

2023-12-12 12:28 UTC, CristianIonutIonescu requested changes
Good work on the code!! As you wrote, there are a few things that still need to be done but there are some other things that need to be done as well:
- to add xml read/write and add/delete objects for final part
- namespaces and scoping
- you have a silent bug when returning values of std::vector, you'll see it when you start implementing your todo
- in your code there's no need for rule of 5, but could you try to force it somewhere to implement it as well?
- [CRITICAL] Read about differences between passing/returning by value  & reference and update your code to respect that. Read about const variables and functions and use it in your code (there are some places where they should be used)

2023-12-12 12:28 UTC, CristianIonutIonescu commented on smart-home-application/Device.cpp
> +std::vector<Sensor> Device::getSensors() {
here you're returning a copy of the sensors that are contained by your device. Read about returning references vs values (a bit similar to passing them as arguments) and how that affects your logic.

Long story short, you have a silent bug in your code waiting to trigger

2023-12-12 12:28 UTC, CristianIonutIonescu commented on smart-home-application/App.h
> +        void newRoom(std::string);
even though Google Style guide recommend using CamelCase notation, I'm ok with this notation as well, but make sure you stay consistent for the rest of the course

2023-12-12 12:28 UTC, CristianIonutIonescu commented on smart-home-application/README.md
> +1. I composed the Device class using a bunch of Sensor objects (using std::vector), so that every device will take the sensors' readings.
Can't the sensors exist independently of the devices?
Eg. I have a very big room that requires more than what an AC unit could sustain therefore I need to install 2. But I don't need 2 sensors to read the room temperature but one to whom both AC units are connected.

I'm not saying it's wrong the way you do it (didn't specify exact requirements) but take it as some food for thought

2023-12-15 08:07 UTC, kyorri commented
Resolved changes for review.

2023-12-15 15:51 UTC, CristianIonutIonescu approved these changes
Nicely done, there are a few other things that need to be solved, but the overall homework is complete. 

PS: I didn't comment on all the things that should be changed, leaving some for the following homeworks :) when we'll discuss about them.

2023-12-15 15:51 UTC, CristianIonutIonescu commented on smart-home-application/Device.cpp
> +Device::~Device() {};
you can make this one default as well

2023-12-15 15:51 UTC, CristianIonutIonescu commented on smart-home-application/Device.cpp
> +void Device::AddSensor(Sensor sensor) {
although is correct, you should pass this as a const reference to improve performance. read a bit more about const and references

this comment applies to other methods as well

2023-12-22 18:40 UTC, closed without merging