feat: implemented separate thread for printing status
CppRemoteLearning/2023 pull request #45
Opened 2024-02-26 19:24 UTC by AntoniaSzecsi

2024-03-04 14:35 UTC, CristianIonutIonescu requested changes
Please address the 2nd comment especially

2024-03-04 14:35 UTC, CristianIonutIonescu commented on main.cc
> +    }
try using 
````
printringThread.join();
````
to block the main thread.

2024-03-04 14:35 UTC, CristianIonutIonescu commented on main.cc
> +    std::thread printingThread(statusThread);
you display on 2 different threads but the action of the main thread is finished by the time you create the display thread.
ControlDevicesDemo should be called during the printing thread run.

2024-03-04 18:07 UTC, AntoniaSzecsi commented on main.cc
> +    std::thread printingThread(statusThread);
ok so basically they have to run simultaneously, on parallel threads. makes more sense like this:)

2024-03-08 11:13 UTC, CristianIonutIonescu approved these changes

2024-03-10 13:50 UTC, merged